# Generated by Django 4.1.6 on 2023-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myinventoryapp', '0002_alter_supplier_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='cost',
            field=models.IntegerField(max_length=300),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='current_quantity',
            field=models.IntegerField(max_length=300),
        ),
    ]
