# Generated by Django 4.1.6 on 2023-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myinventoryapp', '0007_alter_payslip_date_range_alter_payslip_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
