# Generated by Django 4.1.6 on 2023-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myinventoryapp', '0008_alter_employee_allowance_alter_employee_overtime_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='allowance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_pay',
            field=models.FloatField(default=0, null=True),
        ),
    ]
